"""Public Solution Designer contracts."""

from ai_software_engineer.design.agents import (
    DesignerAgentAdapter,
    DesignerAgentConfigurationError,
    DesignerAgentError,
    DesignerAgentErrorCode,
    DesignerAgentFailure,
    DesignerAgentRequest,
    DesignerAgentRequestConflict,
    DesignerAgentResult,
    DesignerAgentRunStatus,
    FakeDesignerAgentAdapter,
    FakeDesignerBehavior,
    FakeDesignerScenario,
)
from ai_software_engineer.design.context import (
    DESIGNER_AGENT_PERMISSIONS,
    DesignContextBuilder,
    DesignContextError,
    DesignContextIntegrityError,
    DesignContextLineageError,
    DesignContextManifest,
    DesignContextSource,
    DesignerAgentPermissions,
)
from ai_software_engineer.design.models import (
    DesignCommitCheckpoint,
    DesignRecordError,
    DesignRecordIntegrityError,
    DesignRunOutcome,
    DesignRunRecord,
)
from ai_software_engineer.design.service import (
    DesignerExecutionError,
    DesignerInputStale,
    DesignerOutputRejected,
    DesignerRunConflict,
    DesignerService,
    DesignerServiceError,
    DesignerServiceResult,
    ProjectStageAdvancePort,
    RunDesignerCommand,
)
from ai_software_engineer.design.store import (
    DesignRecordConflict,
    DesignRecordCorruption,
    DesignRecordNotFound,
    DesignRecordPathError,
    DesignRecordStore,
    FileDesignRecordStore,
)

__all__ = [
    "DESIGNER_AGENT_PERMISSIONS",
    "DesignCommitCheckpoint",
    "DesignContextBuilder",
    "DesignContextError",
    "DesignContextIntegrityError",
    "DesignContextLineageError",
    "DesignContextManifest",
    "DesignContextSource",
    "DesignRecordConflict",
    "DesignRecordCorruption",
    "DesignRecordError",
    "DesignRecordIntegrityError",
    "DesignRecordNotFound",
    "DesignRecordPathError",
    "DesignRecordStore",
    "DesignRunOutcome",
    "DesignRunRecord",
    "DesignerAgentAdapter",
    "DesignerAgentConfigurationError",
    "DesignerAgentError",
    "DesignerAgentErrorCode",
    "DesignerAgentFailure",
    "DesignerAgentPermissions",
    "DesignerAgentRequest",
    "DesignerAgentRequestConflict",
    "DesignerAgentResult",
    "DesignerAgentRunStatus",
    "DesignerExecutionError",
    "DesignerInputStale",
    "DesignerOutputRejected",
    "DesignerRunConflict",
    "DesignerService",
    "DesignerServiceError",
    "DesignerServiceResult",
    "FakeDesignerAgentAdapter",
    "FakeDesignerBehavior",
    "FakeDesignerScenario",
    "FileDesignRecordStore",
    "ProjectStageAdvancePort",
    "RunDesignerCommand",
]
