"""Repository Plane interfaces for role-isolated Git worktrees."""

from ai_software_engineer.git.candidate_commit import (
    CandidateCommitError,
    CandidateCommitRejected,
    CandidateCommitRequest,
    CandidateCommitResult,
    CandidateCommitSkill,
    GitCandidateCommitSkill,
)
from ai_software_engineer.git.capture import WorktreeChangeCapture
from ai_software_engineer.git.policy import (
    CommandPolicyViolation,
    PathPolicyViolation,
    WorkspacePolicy,
    WorkspacePolicyError,
)
from ai_software_engineer.git.ports import (
    GitWorkspace,
    WorktreeRef,
    WorktreeSnapshot,
    WorktreeSpec,
)
from ai_software_engineer.git.worktree import (
    DirtyWorktree,
    GitCommandError,
    GitCommandTimeout,
    GitWorkspaceError,
    GitWorktreeManager,
    InvalidRepository,
    InvalidWorktreeRoot,
    RecoverableGitWorkspace,
    RevisionNotFound,
    UnmanagedWorktree,
    UnsafeRepositoryConfiguration,
    WorktreeAlreadyExists,
    WorktreeCaptureRejected,
    WorktreeIdentityDrift,
    WorktreeNotFound,
    WorktreeRevisionDrift,
    WorktreeSeedRejected,
)

__all__ = [
    "CandidateCommitError",
    "CandidateCommitRejected",
    "CandidateCommitRequest",
    "CandidateCommitResult",
    "CandidateCommitSkill",
    "CommandPolicyViolation",
    "DirtyWorktree",
    "GitCandidateCommitSkill",
    "GitCommandError",
    "GitCommandTimeout",
    "GitWorkspace",
    "GitWorkspaceError",
    "GitWorktreeManager",
    "InvalidRepository",
    "InvalidWorktreeRoot",
    "PathPolicyViolation",
    "RecoverableGitWorkspace",
    "RevisionNotFound",
    "UnmanagedWorktree",
    "UnsafeRepositoryConfiguration",
    "WorkspacePolicy",
    "WorkspacePolicyError",
    "WorktreeAlreadyExists",
    "WorktreeCaptureRejected",
    "WorktreeChangeCapture",
    "WorktreeIdentityDrift",
    "WorktreeNotFound",
    "WorktreeRef",
    "WorktreeRevisionDrift",
    "WorktreeSeedRejected",
    "WorktreeSnapshot",
    "WorktreeSpec",
]
