"""Public Agent Execution Plane contracts and fake/real adapters."""

from ai_software_engineer.agents.fake import FakeAgentAdapter
from ai_software_engineer.agents.models import (
    ROLE_OUTPUT_SCHEMA,
    AgentErrorCode,
    AgentFailure,
    AgentRequest,
    AgentResult,
    AgentRunStatus,
    FakeBehavior,
    FakeScenario,
    RunId,
)
from ai_software_engineer.agents.openai_compatible import (
    ContextPromptBuilder,
    ContextResolver,
    HttpResponse,
    HttpTransport,
    OpenAICompatibleAgentAdapter,
    OpenAICompatibleConfigurationError,
    OpenAICompatibleError,
    PromptBuilder,
    PromptMessage,
    PromptPayload,
    RequestPromptBuilder,
    StoredContextResolver,
    UrllibHttpTransport,
)
from ai_software_engineer.agents.ports import (
    AgentAdapter,
    AgentConfigurationError,
    AgentError,
    AgentRequestConflict,
)

__all__ = [
    "ROLE_OUTPUT_SCHEMA",
    "AgentAdapter",
    "AgentConfigurationError",
    "AgentError",
    "AgentErrorCode",
    "AgentFailure",
    "AgentRequest",
    "AgentRequestConflict",
    "AgentResult",
    "AgentRunStatus",
    "ContextPromptBuilder",
    "ContextResolver",
    "FakeAgentAdapter",
    "FakeBehavior",
    "FakeScenario",
    "HttpResponse",
    "HttpTransport",
    "OpenAICompatibleAgentAdapter",
    "OpenAICompatibleConfigurationError",
    "OpenAICompatibleError",
    "PromptBuilder",
    "PromptMessage",
    "PromptPayload",
    "RequestPromptBuilder",
    "RunId",
    "StoredContextResolver",
    "UrllibHttpTransport",
]
