"""Public Agent Execution Plane contracts and fake/real adapters."""

from ai_software_engineer.agents.codex_cli import (
    CodexCliAgentAdapter,
    CodexCliConfigurationError,
    CodexCliError,
    CodexCommandRunner,
    CodexInvocationResult,
    SubprocessCodexCommandRunner,
)
from ai_software_engineer.agents.fake import FakeAgentAdapter
from ai_software_engineer.agents.fallback import (
    FallbackAgentAdapter,
    FileModelRouteAttemptStore,
    ModelRouteAttempt,
    ModelRouteAttemptConflict,
    ModelRouteAttemptCorruption,
    ModelRouteAttemptStore,
    ModelRouteAttemptStoreError,
    ProviderAgentRoute,
    RouteAttemptOutcome,
)
from ai_software_engineer.agents.models import (
    ROLE_OUTPUT_SCHEMA,
    AgentErrorCode,
    AgentFailure,
    AgentRequest,
    AgentResult,
    AgentRunStatus,
    AgentUsage,
    FakeBehavior,
    FakeScenario,
    RunId,
)
from ai_software_engineer.agents.openai_compatible import (
    ContextPromptBuilder,
    ContextResolver,
    HttpResponse,
    HttpTransport,
    OpenAICompatibleAgentAdapter,
    OpenAICompatibleConfigurationError,
    OpenAICompatibleError,
    PromptBuilder,
    PromptMessage,
    PromptPayload,
    RequestPromptBuilder,
    StoredContextResolver,
    UrllibHttpTransport,
)
from ai_software_engineer.agents.ports import (
    AgentAdapter,
    AgentConfigurationError,
    AgentError,
    AgentRequestConflict,
)
from ai_software_engineer.agents.responses import (
    ResponsesAgentAdapter,
    ResponsesAgentConfigurationError,
    ResponsesAgentError,
)
from ai_software_engineer.agents.structured import (
    CodexCliStructuredModelClient,
    FallbackStructuredModelClient,
    ResponsesStructuredModelClient,
    StructuredModelClient,
    StructuredModelError,
    StructuredModelResult,
    StructuredModelRoute,
)

__all__ = [
    "ROLE_OUTPUT_SCHEMA",
    "AgentAdapter",
    "AgentConfigurationError",
    "AgentError",
    "AgentErrorCode",
    "AgentFailure",
    "AgentRequest",
    "AgentRequestConflict",
    "AgentResult",
    "AgentRunStatus",
    "AgentUsage",
    "CodexCliAgentAdapter",
    "CodexCliConfigurationError",
    "CodexCliError",
    "CodexCliStructuredModelClient",
    "CodexCommandRunner",
    "CodexInvocationResult",
    "ContextPromptBuilder",
    "ContextResolver",
    "FakeAgentAdapter",
    "FakeBehavior",
    "FakeScenario",
    "FallbackAgentAdapter",
    "FallbackStructuredModelClient",
    "FileModelRouteAttemptStore",
    "HttpResponse",
    "HttpTransport",
    "ModelRouteAttempt",
    "ModelRouteAttemptConflict",
    "ModelRouteAttemptCorruption",
    "ModelRouteAttemptStore",
    "ModelRouteAttemptStoreError",
    "OpenAICompatibleAgentAdapter",
    "OpenAICompatibleConfigurationError",
    "OpenAICompatibleError",
    "PromptBuilder",
    "PromptMessage",
    "PromptPayload",
    "ProviderAgentRoute",
    "RequestPromptBuilder",
    "ResponsesAgentAdapter",
    "ResponsesAgentConfigurationError",
    "ResponsesAgentError",
    "ResponsesStructuredModelClient",
    "RouteAttemptOutcome",
    "RunId",
    "StoredContextResolver",
    "StructuredModelClient",
    "StructuredModelError",
    "StructuredModelResult",
    "StructuredModelRoute",
    "SubprocessCodexCommandRunner",
    "UrllibHttpTransport",
]
