"""Browser-only Manager console."""

from .administration import (
    AdministrationError,
    CodexRuntimeStatus,
    ConsoleAdministration,
    CreateProjectRequest,
    DatabaseRuntimeStatus,
    KnowledgeDocumentContentView,
    KnowledgeDocumentView,
    LocalConsoleAdministration,
    ModelRouteRuntimeStatus,
    MySqlConnectionRequest,
    MySqlConnectionResult,
    ProjectSummary,
    RuntimeStatusSnapshot,
    RuntimeVariableUpdate,
    SecretStatus,
    SettingsSnapshot,
    SpecDocumentView,
    TeamSummary,
    UpdateKnowledgeSelectionRequest,
    UpdateSettingsRequest,
    UpdateSpecActivationRequest,
)
from .core import ConsoleCommandRejected, ManagerConsolePort, ProjectConsole
from .manager import ManagerConsoleAdapter, TeamConsoleHost
from .models import (
    CONSOLE_INTENT_ADAPTER,
    ConsoleAction,
    ConsoleApprovalRequest,
    ConsoleCommandResult,
    ConsoleIntent,
    ConsoleOperation,
    ConsoleOperationStatus,
    ContinueDeliveryIntent,
    CreateProjectIntent,
    CreateRequirementIntent,
    ProductApprovalIntent,
    ProductReplyIntent,
)
from .store import (
    ConsoleOperationConflict,
    ConsoleOperationError,
    ConsoleOperationNotFound,
    ConsoleOperationStore,
    FileConsoleOperationStore,
    InMemoryConsoleOperationStore,
)
from .transport import ConsoleApplication, SubmitOperation, TeamReader, create_console_app

__all__ = [
    "CONSOLE_INTENT_ADAPTER",
    "AdministrationError",
    "CodexRuntimeStatus",
    "ConsoleAction",
    "ConsoleAdministration",
    "ConsoleApplication",
    "ConsoleApprovalRequest",
    "ConsoleCommandRejected",
    "ConsoleCommandResult",
    "ConsoleIntent",
    "ConsoleOperation",
    "ConsoleOperationConflict",
    "ConsoleOperationError",
    "ConsoleOperationNotFound",
    "ConsoleOperationStatus",
    "ConsoleOperationStore",
    "ContinueDeliveryIntent",
    "CreateProjectIntent",
    "CreateProjectRequest",
    "CreateRequirementIntent",
    "DatabaseRuntimeStatus",
    "FileConsoleOperationStore",
    "InMemoryConsoleOperationStore",
    "KnowledgeDocumentContentView",
    "KnowledgeDocumentView",
    "LocalConsoleAdministration",
    "ManagerConsoleAdapter",
    "ManagerConsolePort",
    "ModelRouteRuntimeStatus",
    "MySqlConnectionRequest",
    "MySqlConnectionResult",
    "ProductApprovalIntent",
    "ProductReplyIntent",
    "ProjectConsole",
    "ProjectSummary",
    "RuntimeStatusSnapshot",
    "RuntimeVariableUpdate",
    "SecretStatus",
    "SettingsSnapshot",
    "SpecDocumentView",
    "SubmitOperation",
    "TeamConsoleHost",
    "TeamReader",
    "TeamSummary",
    "UpdateKnowledgeSelectionRequest",
    "UpdateSettingsRequest",
    "UpdateSpecActivationRequest",
    "create_console_app",
]
