"""Browser-only Project Manager console."""

from .administration import (
    AdministrationError,
    CompanySummary,
    ConsoleAdministration,
    CreateCompanyRequest,
    KnowledgeDocumentView,
    LocalConsoleAdministration,
    SecretStatus,
    SettingsSnapshot,
    UpdateSettingsRequest,
)
from .core import ConsoleCommandRejected, ProjectConsole, ProjectManagerConsolePort
from .models import (
    CONSOLE_INTENT_ADAPTER,
    ConsoleAction,
    ConsoleApprovalRequest,
    ConsoleCommandResult,
    ConsoleIntent,
    ConsoleOperation,
    ConsoleOperationStatus,
    ContinueDeliveryIntent,
    CreateRequirementProjectIntent,
    ProductApprovalIntent,
    ProductReplyIntent,
)
from .project_manager import OrganizationTeamConsoleHost, ProjectManagerConsoleAdapter
from .store import (
    ConsoleOperationConflict,
    ConsoleOperationError,
    ConsoleOperationNotFound,
    ConsoleOperationStore,
    FileConsoleOperationStore,
    InMemoryConsoleOperationStore,
)
from .transport import ConsoleApplication, SubmitOperation, TeamReader, create_console_app

__all__ = [
    "CONSOLE_INTENT_ADAPTER",
    "AdministrationError",
    "CompanySummary",
    "ConsoleAction",
    "ConsoleAdministration",
    "ConsoleApplication",
    "ConsoleApprovalRequest",
    "ConsoleCommandRejected",
    "ConsoleCommandResult",
    "ConsoleIntent",
    "ConsoleOperation",
    "ConsoleOperationConflict",
    "ConsoleOperationError",
    "ConsoleOperationNotFound",
    "ConsoleOperationStatus",
    "ConsoleOperationStore",
    "ContinueDeliveryIntent",
    "CreateCompanyRequest",
    "CreateRequirementProjectIntent",
    "FileConsoleOperationStore",
    "InMemoryConsoleOperationStore",
    "KnowledgeDocumentView",
    "LocalConsoleAdministration",
    "OrganizationTeamConsoleHost",
    "ProductApprovalIntent",
    "ProductReplyIntent",
    "ProjectConsole",
    "ProjectManagerConsoleAdapter",
    "ProjectManagerConsolePort",
    "SecretStatus",
    "SettingsSnapshot",
    "SubmitOperation",
    "TeamReader",
    "UpdateSettingsRequest",
    "create_console_app",
]
