"""Public domain contract for ai-software-engineer v0.1."""

from ai_software_engineer.domain.agent import AgentDefinition, AgentPermissions
from ai_software_engineer.domain.artifact import (
    AgentProducer,
    Artifact,
    ArtifactEnvelope,
    ArtifactIntegrity,
    ChangedFile,
    Evidence,
    Finding,
    ImplementationAcceptanceMapping,
    ImplementationReportArtifact,
    ImplementationReportContent,
    ImplementationTestRun,
    PlanAcceptanceMapping,
    PlanArtifact,
    PlanContent,
    PlanRisk,
    PlanStep,
    QaCriterionResult,
    QaReportArtifact,
    QaReportContent,
    QaTestRun,
    ReviewReportArtifact,
    ReviewReportContent,
    validate_artifact,
)
from ai_software_engineer.domain.enums import (
    AgentRole,
    ArtifactKind,
    BrainTier,
    ChangeType,
    EvidenceType,
    FindingSeverity,
    ImplementationTestStatus,
    ModelRouteReason,
    NetworkAccess,
    QaCriterionStatus,
    QaReportStatus,
    QaTestStatus,
    ReviewDimension,
    ReviewVerdict,
    RiskTier,
    TaskStatus,
    WorkItemStatus,
)
from ai_software_engineer.domain.event import StateEvent
from ai_software_engineer.domain.identity import ContextId, ProjectId, RunId
from ai_software_engineer.domain.task import AcceptanceCriterion, Task, TaskConstraints
from ai_software_engineer.domain.workforce import (
    AgentProfile,
    AgentRunAllocation,
    AssignmentConflict,
    ModelPolicy,
    ModelRoute,
    ModelSelection,
    RiskModelFloor,
    RoleAssignment,
    RunDemand,
    TaskLease,
    WorkItem,
    is_waiting,
    lease_is_active,
    validate_assignment_independence,
)

Agent = AgentDefinition

__all__ = [
    "AcceptanceCriterion",
    "Agent",
    "AgentDefinition",
    "AgentPermissions",
    "AgentProducer",
    "AgentProfile",
    "AgentRole",
    "AgentRunAllocation",
    "Artifact",
    "ArtifactEnvelope",
    "ArtifactIntegrity",
    "ArtifactKind",
    "AssignmentConflict",
    "BrainTier",
    "ChangeType",
    "ChangedFile",
    "ContextId",
    "Evidence",
    "EvidenceType",
    "Finding",
    "FindingSeverity",
    "ImplementationAcceptanceMapping",
    "ImplementationReportArtifact",
    "ImplementationReportContent",
    "ImplementationTestRun",
    "ImplementationTestStatus",
    "ModelPolicy",
    "ModelRoute",
    "ModelRouteReason",
    "ModelSelection",
    "NetworkAccess",
    "PlanAcceptanceMapping",
    "PlanArtifact",
    "PlanContent",
    "PlanRisk",
    "PlanStep",
    "ProjectId",
    "QaCriterionResult",
    "QaCriterionStatus",
    "QaReportArtifact",
    "QaReportContent",
    "QaReportStatus",
    "QaTestRun",
    "QaTestStatus",
    "ReviewDimension",
    "ReviewReportArtifact",
    "ReviewReportContent",
    "ReviewVerdict",
    "RiskModelFloor",
    "RiskTier",
    "RoleAssignment",
    "RunDemand",
    "RunId",
    "StateEvent",
    "Task",
    "TaskConstraints",
    "TaskLease",
    "TaskStatus",
    "WorkItem",
    "WorkItemStatus",
    "is_waiting",
    "lease_is_active",
    "validate_artifact",
    "validate_assignment_independence",
]
