"""Public domain contract for ai-software-engineer v0.1."""

from ai_software_engineer.domain.agent import AgentDefinition, AgentPermissions
from ai_software_engineer.domain.artifact import (
    AgentProducer,
    Artifact,
    ArtifactEnvelope,
    ArtifactIntegrity,
    ChangedFile,
    Evidence,
    Finding,
    ImplementationAcceptanceMapping,
    ImplementationReportArtifact,
    ImplementationReportContent,
    ImplementationTestRun,
    PlanAcceptanceMapping,
    PlanArtifact,
    PlanContent,
    PlanRisk,
    PlanStep,
    QaCriterionResult,
    QaReportArtifact,
    QaReportContent,
    QaTestRun,
    ReviewReportArtifact,
    ReviewReportContent,
    validate_artifact,
)
from ai_software_engineer.domain.enums import (
    AgentRole,
    ArtifactKind,
    ChangeType,
    EvidenceType,
    FindingSeverity,
    ImplementationTestStatus,
    NetworkAccess,
    QaCriterionStatus,
    QaReportStatus,
    QaTestStatus,
    ReviewDimension,
    ReviewVerdict,
    TaskStatus,
)
from ai_software_engineer.domain.event import StateEvent
from ai_software_engineer.domain.task import AcceptanceCriterion, Task, TaskConstraints

Agent = AgentDefinition

__all__ = [
    "AcceptanceCriterion",
    "Agent",
    "AgentDefinition",
    "AgentPermissions",
    "AgentProducer",
    "AgentRole",
    "Artifact",
    "ArtifactEnvelope",
    "ArtifactIntegrity",
    "ArtifactKind",
    "ChangeType",
    "ChangedFile",
    "Evidence",
    "EvidenceType",
    "Finding",
    "FindingSeverity",
    "ImplementationAcceptanceMapping",
    "ImplementationReportArtifact",
    "ImplementationReportContent",
    "ImplementationTestRun",
    "ImplementationTestStatus",
    "NetworkAccess",
    "PlanAcceptanceMapping",
    "PlanArtifact",
    "PlanContent",
    "PlanRisk",
    "PlanStep",
    "QaCriterionResult",
    "QaCriterionStatus",
    "QaReportArtifact",
    "QaReportContent",
    "QaReportStatus",
    "QaTestRun",
    "QaTestStatus",
    "ReviewDimension",
    "ReviewReportArtifact",
    "ReviewReportContent",
    "ReviewVerdict",
    "StateEvent",
    "Task",
    "TaskConstraints",
    "TaskStatus",
    "validate_artifact",
]
